import { NextResponse } from "next/server";

// Full editor presets with all configuration options
const editorPresets = [
  {
    id: "minimal-clean",
    label: "Minimal Clean",
    category: "professional",
    description: "Clean, distraction-free look for serious content",
    config: {
      stickerAnim: "static",
      stickerScale: 0.9,
      stickerGlowIntensity: 0.2,
      stickerBorderWidth: 2,
      showStickerLabels: false,
      subtitleSize: 42,
      subtitleY: 68,
      subtitleFontFamily: "Inter",
      subtitleFontWeight: 500,
      subtitleShadowBlur: 4,
      subtitleBackgroundOpacity: 0.6,
      subtitleBackgroundBlur: 12,
      bgDimOpacity: 0.5,
      bgBlur: 2,
      showProgressBar: false,
      showIntroBadge: false,
      transitionStyle: "fade",
    },
  },
  {
    id: "social-energy",
    label: "Social Energy",
    category: "social",
    description: "High-energy style for viral social content",
    config: {
      stickerAnim: "bounce",
      stickerScale: 1.1,
      stickerGlowIntensity: 0.8,
      stickerBorderWidth: 4,
      showStickerLabels: true,
      subtitleSize: 56,
      subtitleY: 62,
      subtitleFontFamily: "Bebas Neue",
      subtitleFontWeight: 700,
      subtitleLetterSpacing: 2,
      subtitleShadowBlur: 12,
      subtitleOutlineWidth: 3,
      bgDimOpacity: 0.3,
      bgSaturation: 1.2,
      bgContrast: 1.1,
      showProgressBar: true,
      showIntroBadge: true,
      transitionStyle: "zoom",
      transitionDuration: 0.2,
    },
  },
  {
    id: "podcast-style",
    label: "Podcast Style",
    category: "podcast",
    description: "Warm, conversational feel for podcast clips",
    config: {
      stickerAnim: "float",
      stickerScale: 1.0,
      stickerGlowIntensity: 0.4,
      stickerBorderWidth: 3,
      showStickerLabels: true,
      subtitleSize: 44,
      subtitleY: 70,
      subtitleFontFamily: "Montserrat",
      subtitleFontWeight: 600,
      subtitleLineHeight: 1.3,
      subtitleShadowBlur: 6,
      bgDimOpacity: 0.55,
      bgBrightness: 0.9,
      showProgressBar: true,
      progressBarHeight: 3,
      showIntroBadge: false,
      transitionStyle: "fade",
    },
  },
  {
    id: "news-editorial",
    label: "News Editorial",
    category: "professional",
    description: "Authoritative look for news and editorial content",
    config: {
      stickerAnim: "slide",
      stickerScale: 0.85,
      stickerGlowIntensity: 0.3,
      stickerBorderWidth: 2,
      showStickerLabels: true,
      subtitleSize: 40,
      subtitleY: 75,
      subtitleFontFamily: "Roboto",
      subtitleFontWeight: 500,
      subtitleBackgroundOpacity: 0.8,
      subtitleBackgroundBlur: 0,
      subtitlePadding: 16,
      bgDimOpacity: 0.6,
      bgSaturation: 0.9,
      showProgressBar: true,
      progressBarHeight: 2,
      progressBarY: 95,
      showIntroBadge: false,
      transitionStyle: "slide-up",
    },
  },
  {
    id: "cinematic-drama",
    label: "Cinematic Drama",
    category: "cinematic",
    description: "Dramatic, movie-trailer inspired look",
    config: {
      stickerAnim: "pulse",
      stickerScale: 1.15,
      stickerGlowIntensity: 0.7,
      stickerBorderWidth: 0,
      showStickerLabels: false,
      subtitleSize: 52,
      subtitleY: 60,
      subtitleFontFamily: "Playfair Display",
      subtitleFontWeight: 700,
      subtitleLetterSpacing: 1,
      subtitleShadowBlur: 20,
      subtitleShadowOffsetY: 4,
      bgDimOpacity: 0.7,
      bgContrast: 1.15,
      bgBrightness: 0.85,
      showProgressBar: false,
      showIntroBadge: true,
      introBadgeDuration: 4,
      transitionStyle: "blur",
      transitionDuration: 0.5,
    },
  },
  {
    id: "education-focus",
    label: "Education Focus",
    category: "education",
    description: "Clear, readable style for educational content",
    config: {
      stickerAnim: "static",
      stickerScale: 0.95,
      stickerGlowIntensity: 0.3,
      stickerBorderWidth: 3,
      showStickerLabels: true,
      subtitleSize: 46,
      subtitleY: 65,
      subtitleFontFamily: "Open Sans",
      subtitleFontWeight: 600,
      subtitleLineHeight: 1.4,
      subtitleShadowBlur: 6,
      subtitleBackgroundOpacity: 0.5,
      subtitleBackgroundBlur: 8,
      bgDimOpacity: 0.45,
      showProgressBar: true,
      progressBarHeight: 4,
      showIntroBadge: true,
      introBadgeDuration: 2,
      transitionStyle: "fade",
    },
  },
  {
    id: "tiktok-viral",
    label: "TikTok Viral",
    category: "social",
    description: "Attention-grabbing style optimized for TikTok",
    config: {
      stickerAnim: "shake",
      stickerScale: 1.2,
      stickerGlowIntensity: 0.9,
      stickerBorderWidth: 5,
      showStickerLabels: true,
      subtitleSize: 64,
      subtitleY: 58,
      subtitleFontFamily: "Anton",
      subtitleFontWeight: 700,
      subtitleLetterSpacing: 1,
      subtitleOutlineWidth: 4,
      subtitleOutlineColor: "#000000",
      bgDimOpacity: 0.2,
      bgSaturation: 1.3,
      bgScale: 1.1,
      showProgressBar: false,
      showIntroBadge: true,
      transitionStyle: "zoom",
      transitionDuration: 0.15,
    },
  },
  {
    id: "storytelling",
    label: "Storytelling",
    category: "narrative",
    description: "Immersive style for story-driven content",
    config: {
      stickerAnim: "float",
      stickerScale: 1.0,
      stickerGlowIntensity: 0.5,
      stickerBorderWidth: 2,
      showStickerLabels: true,
      subtitleSize: 48,
      subtitleY: 68,
      subtitleFontFamily: "Lato",
      subtitleFontWeight: 600,
      subtitleLineHeight: 1.35,
      subtitleShadowBlur: 10,
      bgDimOpacity: 0.5,
      bgBlur: 1,
      showProgressBar: true,
      progressBarHeight: 3,
      showIntroBadge: false,
      transitionStyle: "fade",
      transitionDuration: 0.4,
      speakerHighlightDelay: 0.1,
    },
  },
];

const categories = [
  { id: "professional", label: "Professional", description: "Clean looks for business content" },
  { id: "social", label: "Social Media", description: "High-energy viral styles" },
  { id: "podcast", label: "Podcast", description: "Warm, conversational feels" },
  { id: "cinematic", label: "Cinematic", description: "Dramatic, movie-inspired" },
  { id: "education", label: "Education", description: "Clear and readable" },
  { id: "narrative", label: "Narrative", description: "Immersive storytelling" },
];

/**
 * GET /api/editor/presets
 * Get available editor presets and configuration schema
 */
export async function GET() {
  return NextResponse.json({
    presets: editorPresets,
    categories,
    schema: {
      stickerAnimations: ["bounce", "slide", "float", "pulse", "shake", "static"],
      fontFamilies: [
        "Inter",
        "Montserrat",
        "Poppins",
        "Roboto",
        "Open Sans",
        "Lato",
        "Oswald",
        "Playfair Display",
        "Bebas Neue",
        "Anton",
      ],
      transitionStyles: ["none", "fade", "slide-up", "slide-down", "zoom", "blur"],
      textAlignOptions: ["left", "center", "right"],
      watermarkPositions: ["top-left", "top-right", "bottom-left", "bottom-right"],
      ranges: {
        stickerScale: { min: 0.5, max: 2.0, step: 0.05 },
        stickerGlowIntensity: { min: 0, max: 1, step: 0.1 },
        stickerBorderWidth: { min: 0, max: 10, step: 1 },
        stickerOffset: { min: -200, max: 200, step: 5 },
        subtitleSize: { min: 18, max: 120, step: 2 },
        subtitleY: { min: 0, max: 100, step: 1 },
        subtitleFontWeight: { min: 400, max: 900, step: 100 },
        subtitleLetterSpacing: { min: -2, max: 10, step: 0.5 },
        subtitleLineHeight: { min: 0.8, max: 2, step: 0.1 },
        subtitlePadding: { min: 0, max: 100, step: 5 },
        subtitleShadowBlur: { min: 0, max: 30, step: 1 },
        subtitleOutlineWidth: { min: 0, max: 10, step: 0.5 },
        bgDimOpacity: { min: 0, max: 1, step: 0.05 },
        bgBlur: { min: 0, max: 30, step: 1 },
        bgSaturation: { min: 0, max: 2, step: 0.1 },
        bgBrightness: { min: 0, max: 2, step: 0.1 },
        bgContrast: { min: 0, max: 2, step: 0.1 },
        bgScale: { min: 1, max: 1.5, step: 0.05 },
        progressBarHeight: { min: 2, max: 12, step: 1 },
        transitionDuration: { min: 0.1, max: 1, step: 0.05 },
        watermarkOpacity: { min: 0, max: 1, step: 0.1 },
        watermarkSize: { min: 8, max: 24, step: 1 },
      },
    },
  });
}
